### ISSUE TITLE
Redirect does not work

### ISSUE THREAD

**Issue by 4ndir** [unimitysolutionspvtltd/basiccart#8]
Hi there and thanks a lot for the module! 

I put `cart` to `Add to cart redirect` but the redirect does not work. example.com/cart does work though. 

Console shows a 404 on every page load: 

> http://example.com/modules/contrib/basiccart/dependencies?v=1.x 404 (Not Found)

I installed the module by copying to the contrib dir and and enabled the module through the modules admin page.

**Comment by karthikeyan-manivasagam** [comment]
HI

Redirect issue fixed **"I put cart to Add to cart redirect but the redirect does not work. example.com/cart does work though."**

**Comment by 4ndir** [comment]
Thanks! Unfortunatly it does not work for guests. As admin it works nicely.

**Comment by karthikeyan-manivasagam** [comment]
Did you Try enabling permissions

**Comment by karthikeyan-manivasagam** [comment]
Clear the cache as well

**Comment by 4ndir** [comment]
I enabled all permissions under Basic Cart and cleared caches multiple times.

**Comment by 4ndir** [comment]
Hm, sorry. It was browser caching. another browser did it.

**Comment by 4ndir** [comment]
Thanks a lot!
